# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples (int)
#' @param thin the number of between-sample random numbers (int)
#' @param mu1 the mean of first marginal value (double)
#' @param mu2 the mean of second marginal value (double)
#' @param sigma1 the variance of first marginal value (double)
#' @param sigma2 the variance of second marginal value (double)
#' @param rho correlation (double)
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <-gibbsC(5000,2,0,0,1,1,.9)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, thin, mu1, mu2, sigma1, sigma2, rho) {
    .Call(`_StatComp22037_gibbsC`, N, thin, mu1, mu2, sigma1, sigma2, rho)
}

rcpp_hello_world <- function() {
    .Call(`_StatComp22037_rcpp_hello_world`)
}

